Fix post-extract script

diff --git a/post-extract b/post-extract
--- a/post-extract
+++ b/post-extract
@@ -1,19 +1,22 @@
 #!/usr/bin/env bash
-# set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
-# source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
+
+# Halt on error and support tracing.
+set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
+
+# Find and read configuration file.
+# shellcheck source=commands
+source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/config"
 
 # APP="$1"
-# TMP_WORK_DIR="$2"
+TMP_WORK_DIR="$2"
+TEMPLATE_FILE="$PLUGIN_DATA_ROOT/nginx.conf.sigil"
 
-# NGINX_TEMPLATE="$PLUGIN_AVAILABLE_PATH/h5bp-server-config/nginx.conf.sigil.default"
-
-# if [ ! -f "$DOKKU_ROOT/$APP/nginx.conf.sigil" ]; then
-# 	if grep -q "log_format custom" /etc/nginx/nginx.conf; then
-# 		cp $NGINX_TEMPLATE "$TMP_WORK_DIR/nginx.conf.sigil"
-# 		dokku_log_info1 "Custom nginx.conf.sigil deployed."	
-# 	else
-# 		dokku_log_fail "Cannot install custom logging without `log_format custom` in /etc/nginx/nginx.conf"
-# 	fi
-# else 
-# 	dokku_log_info1 "nginx.conf.sigil already present in app, will not deploy default."	
-# fi
+if [[ -f "$TEMPLATE_FILE" ]]; then
+    # If the application aready has a template in its repository, bail.
+    if [[ ! -f "$TMP_WORK_DIR/nginx.conf.sigil" ]]; then
+        cp "$TEMPLATE_FILE" "$TMP_WORK_DIR/nginx.conf.sigil"
+        dokku_log_info1 "Custom nginx.conf.sigil deployed."	
+    else 
+        dokku_log_info1 "nginx.conf.sigil already present in app. Skipping custom template."	
+    fi
+fi
